# Generated by Django 5.0.6 on 2024-05-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_group_name'),
        ('app', '0007_alter_group_name'),
    ]

    operations = [
    ]
