# Generated by Django 5.0.6 on 2024-05-31 16:31

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_group_admin_group_new_group_name_alter_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=200
            ),
        ),
    ]
