# Generated by Django 5.0.6 on 2024-06-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_group_name'),
        ('app', '0013_remove_message_users_online_group_users_online_and_more'),
        ('app', '0014_message_is_invitation_alter_group_name'),
    ]

    operations = [
    ]
