# Generated by Django 5.0.6 on 2024-06-02 22:24

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_group_banned_users_alter_group_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=200
            ),
        ),
        migrations.DeleteModel(
            name="FriendList",
        ),
    ]
